namespace:
  name: prod

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

service:
  port: 80
  type: ClusterIP

resources: 
  request:
    cpu: 70m
    memory: 256Mi
    
configmap:
  data: "version: 1.17.0"

replicaCount: 2
